/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	k8scnicncfiov1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkAttachmentDefinitionLister helps list NetworkAttachmentDefinitions.
// All objects returned here must be treated as read-only.
type NetworkAttachmentDefinitionLister interface {
	// List lists all NetworkAttachmentDefinitions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*k8scnicncfiov1.NetworkAttachmentDefinition, err error)
	// NetworkAttachmentDefinitions returns an object that can list and get NetworkAttachmentDefinitions.
	NetworkAttachmentDefinitions(namespace string) NetworkAttachmentDefinitionNamespaceLister
	NetworkAttachmentDefinitionListerExpansion
}

// networkAttachmentDefinitionLister implements the NetworkAttachmentDefinitionLister interface.
type networkAttachmentDefinitionLister struct {
	listers.ResourceIndexer[*k8scnicncfiov1.NetworkAttachmentDefinition]
}

// NewNetworkAttachmentDefinitionLister returns a new NetworkAttachmentDefinitionLister.
func NewNetworkAttachmentDefinitionLister(indexer cache.Indexer) NetworkAttachmentDefinitionLister {
	return &networkAttachmentDefinitionLister{listers.New[*k8scnicncfiov1.NetworkAttachmentDefinition](indexer, k8scnicncfiov1.Resource("networkattachmentdefinition"))}
}

// NetworkAttachmentDefinitions returns an object that can list and get NetworkAttachmentDefinitions.
func (s *networkAttachmentDefinitionLister) NetworkAttachmentDefinitions(namespace string) NetworkAttachmentDefinitionNamespaceLister {
	return networkAttachmentDefinitionNamespaceLister{listers.NewNamespaced[*k8scnicncfiov1.NetworkAttachmentDefinition](s.ResourceIndexer, namespace)}
}

// NetworkAttachmentDefinitionNamespaceLister helps list and get NetworkAttachmentDefinitions.
// All objects returned here must be treated as read-only.
type NetworkAttachmentDefinitionNamespaceLister interface {
	// List lists all NetworkAttachmentDefinitions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*k8scnicncfiov1.NetworkAttachmentDefinition, err error)
	// Get retrieves the NetworkAttachmentDefinition from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*k8scnicncfiov1.NetworkAttachmentDefinition, error)
	NetworkAttachmentDefinitionNamespaceListerExpansion
}

// networkAttachmentDefinitionNamespaceLister implements the NetworkAttachmentDefinitionNamespaceLister
// interface.
type networkAttachmentDefinitionNamespaceLister struct {
	listers.ResourceIndexer[*k8scnicncfiov1.NetworkAttachmentDefinition]
}
